apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-app
  namespace: test3
spec:
  params:
    - description: The name of deployment
      name: DEPLOYMENT_NAME
      type: string
    - description: The namespace for the deployment
      name: NAMESPACE
      type: string
    - description: The subdirectory in which app deployments manifests are stored
      name: MANIFESTS_DIR
      type: string
  steps:
    - computeResources: {}
      image: 'image-registry.openshift-image-registry.svc:5000/openshift/cli'
      name: apply-manifests
      script: |

        find $(workspaces.source.path)

        ls
        oc apply -f $(params.MANIFESTS_DIR) -n $(params.NAMESPACE)
      workingDir: $(workspaces.source.path)
  workspaces:
    - description: The workspace consisting of maven project.
      name: source

