kind: Deployment
apiVersion: apps/v1
metadata:
  name: test4
  namespace: test3
  labels:
    app: javaimage
    app.kubernetes.io/component: javaimage
    app.kubernetes.io/instance: javaimage
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: javaimage
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: javaimage
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: javaimage
          image: >-
            image-registry.openshift-image-registry.svc:5000/test3/javaimage@sha256:26059b7f1b743e19eb2477c2a63b97dbd85af80835ffd5277c3e993e07d632f8
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  
